---
title: "cuts"
---


# CI for mu

# Why it works

The confidence interval for $\mu$ requires the $t$ distribution, which is a modification of the normal distribution. Under the conditions of the CLT (large, random sample), $\bar{y}$ is approximately normally distributed, or, when standardized:

$$
\frac{\bar{y} - \mu}{\sigma/\sqrt{n}} \sim Z
$$

However, $\sigma$ is the *population* standard deviation, which we do not know. We can replace $\sigma$ with its estimate, $s$, but this adds extra uncertainty and variability to our statistic. The new statistic is no longer a $Z$ distribution, but a $t$ distribution. Ultimately, we have

$$
\frac{\bar{y} - \mu}{s/\sqrt{n}} \sim t^{(n-1)}
$$

where $n-1$ are the degrees of freedom of the $t$ distribution.

We obtain a 95% confidence interval by starting with the probability statement

$$
P\left( -t_{0.025}^{(n-1)} < \frac{\bar{y} - \mu}{s/\sqrt{n}} < t_{0.025}^{(n-1)} \right) = 0.95
$$

Then we can solve the inequality in the probability to obtain just $\mu$ on the inside^[Steps: (1) multiply by $\frac{s}{\sqrt{n}}$; (2) subtract $\bar{y}$; (3) multiply by $-1$, remembering to switch the direction of the inequality signs]:

$$
P(\bar{y} - t_{0.025}^{(n-1)}\frac{s}{\sqrt{n}} < \mu < \bar{y} + t_{0.025}^{(n-1)}\frac{s}{\sqrt{n}}) = 0.95
$$

So, there is a 95% chance that $\mu$ is between $\bar{y} - t_{0.025}^{(n-1)}\frac{s}{\sqrt{n}}$ and $\bar{y} + t_{0.025}^{(n-1)}\frac{s}{\sqrt{n}}$. Making the result a bit more compact, the 95% confidence interval for $\mu$ is

$$
\bar{y} \pm t_{0.025}^{(n-1)} \frac{s}{\sqrt{n-1}}
$$
